/**
 * Andi VN - Enemy Data
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by tools/build_story_from_md.py
 * 
 * Edit enemy files in enemies/*.md instead.
 */

const enemies = {
  "agnes_hr": {
    "id": "agnes_hr",
    "name": "Agnes (HR)",
    "sprite": "agnes_blocking.svg",
    "hp": 22,
    "ac": 11,
    "attack_bonus": 3,
    "damage": "d6",
    "type": "physical",
    "stagger_threshold": 50,
    "ai": "default",
    "dialogue": {
      "attack_default": [
        "Time for your annual review!",
        "This is going in your file!",
        "HR always wins!"
      ],
      "attack_player_low_hp": [
        "Your termination is imminent!",
        "Should've read the employee handbook!",
        "Exit interview time!"
      ],
      "attack_player_healed": [
        "Wellness programs won't save you!",
        "Self-care? In THIS economy?",
        "Band-aids don't fix policy violations!"
      ],
      "attack_player_defended": [
        "No hiding behind bureaucracy!",
        "Your shield is not OSHA-approved!",
        "Defense won't help your performance review!"
      ],
      "attack_player_missed": [
        "Missed! Just like your deadlines!",
        "That's going in your file!",
        "Attendance issues AND accuracy issues?"
      ],
      "attack_got_hit": [
        "Ow! That's workplace violence!",
        "I'm filing a complaint!",
        "HR will remember this!"
      ],
      "attack_got_crit": [
        "That's... actually impressive.",
        "Noted for your performance review!",
        "Fine! Gloves are OFF!"
      ],
      "attack_self_low_hp": [
        "I won't be outsourced!",
        "HR never surrenders!",
        "You can't fire ME!"
      ],
      "attack_has_status": [
        "This is a hostile work environment!",
        "I'm documenting EVERYTHING!",
        "Workers' comp will hear about this!"
      ],
      "attack_player_stunned": [
        "Mandatory meeting time!",
        "No skipping this one!",
        "Captive audience!"
      ],
      "battle_start": [
        "Your resignation has been... REJECTED!",
        "Let's discuss your future here!",
        "Time for your exit interview!"
      ],
      "victory": [
        "Back to the cubicle with you!",
        "HR: 1, Employee: 0",
        "Your termination is complete!"
      ],
      "defeat": [
        "This... isn't... protocol...",
        "I'll be back... with forms...",
        "HR will hear about this!"
      ],
      "move_performance_review": [
        "Let's review your quarterly goals!",
        "Your metrics are... disappointing."
      ],
      "move_break_room_retreat": [
        "Coffee break!",
        "Even HR needs a breather..."
      ]
    },
    "moves": [
      {
        "name": "HR Memo",
        "damage": "d6",
        "type": "physical",
        "description": "A sharply worded memo flies your way!"
      },
      {
        "name": "Performance Review",
        "damage": "2d4",
        "type": "psychic",
        "statusEffect": {
          "type": "stun",
          "chance": 0.15
        },
        "description": "Agnes critiques your life choices."
      },
      {
        "name": "Policy Enforcement",
        "damage": "d4",
        "type": "physical",
        "statusEffect": {
          "type": "bleed",
          "chance": 0.25
        },
        "description": "Red tape cuts deep!"
      },
      {
        "name": "Break Room Retreat",
        "isHeal": true,
        "healAmount": "1d4+1",
        "description": "Agnes takes a coffee break."
      }
    ],
    "intents": [
      {
        "id": "call_intern",
        "type": "summon",
        "chance": 0.15,
        "minTurn": 3,
        "cooldown": 5,
        "prepTurns": 1,
        "dialogue": "INTERN! Get in here NOW!",
        "executeDialogue": "You wanted to see me, Agnes?",
        "skill": {
          "name": "Call Intern",
          "damage": 0,
          "type": "physical",
          "isSummon": true,
          "summonId": "office_intern",
          "description": "Agnes summons an intern to assist her."
        }
      },
      {
        "id": "termination_notice",
        "type": "big_attack",
        "chance": 0.2,
        "minTurn": 2,
        "cooldown": 4,
        "hpThreshold": 0.7,
        "prepTurns": 1,
        "dialogue": "I'm preparing your TERMINATION NOTICE!",
        "executeDialogue": "Your employment is TERMINATED!",
        "skill": {
          "name": "Termination Notice",
          "damage": "3d6",
          "type": "psychic",
          "description": "A devastating psychological attack. You should have defended!"
        }
      },
      {
        "id": "policy_barrage",
        "type": "multi_hit",
        "chance": 0.18,
        "minTurn": 4,
        "cooldown": 5,
        "prepTurns": 1,
        "dialogue": "Let me pull up ALL your violations...",
        "executeDialogue": "Violation 1... 2... 3... 4!",
        "skill": {
          "name": "Policy Barrage",
          "damage": "d4",
          "type": "physical",
          "hits": 4,
          "description": "A rapid barrage of policy violations!"
        }
      }
    ],
    "description": "Agnes from HR. The final boss of every office worker's nightmare. Her weapon? Paperwork. Her armor? Policy. Her weakness? Actual human connection (which she lacks)."
  }
};

// Export for use by engine
if (typeof module !== "undefined" && module.exports) {
    module.exports = { enemies };
}
