/**
 * Andi VN - Player Data
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by tools/build_story_from_md.py
 * 
 * Edit player/player.md instead.
 */

const playerConfig = {
  "name": "Andi",
  "hp": 20,
  "mana": 10,
  "ac": 11,
  "attack_bonus": 2,
  "damage": "1d6",
  "type": "physical",
  "stagger_threshold": 100,
  "limit_break": {
    "name": "Overdrive",
    "damage": "3d8",
    "type": "physical",
    "description": "A devastating attack that unleashes all your power!"
  },
  "skills": [
    {
      "id": "power_strike",
      "name": "Power Strike",
      "damage": "2d6",
      "type": "physical",
      "manaCost": 3,
      "description": "A powerful blow that deals extra damage."
    },
    {
      "id": "heal",
      "name": "Heal",
      "healAmount": "2d4",
      "manaCost": 4,
      "description": "Restore some health."
    },
    {
      "id": "fire_bolt",
      "name": "Fire Bolt",
      "damage": "1d8",
      "type": "fire",
      "manaCost": 2,
      "description": "Launch a bolt of fire at the enemy."
    },
    {
      "id": "ice_shard",
      "name": "Ice Shard",
      "damage": "1d6",
      "type": "ice",
      "manaCost": 2,
      "statusEffect": {
        "type": "slow",
        "chance": 0.25
      },
      "description": "A shard of ice that may slow the target."
    },
    {
      "id": "summon_keyboard",
      "name": "Summon Keyboard",
      "isSummon": true,
      "summonId": "sentient_keyboard",
      "manaCost": 5,
      "description": "Summon a sentient mechanical keyboard to type furiously at enemies!"
    }
  ]
};

// Export for use by engine
if (typeof module !== "undefined" && module.exports) {
    module.exports = { playerConfig };
}
