/**
 * Andi VN - Story Data
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by tools/build_story_from_md.py
 * 
 * Edit scene files in scenes/*.md instead.
 */

const story = {
  "agnes_battle": {
    "id": "agnes_battle",
    "bg": "hallway_red_alert.jpg",
    "music": "BOSS_TIME.mp3",
    "chars": [
      "agnes_blocking.svg"
    ],
    "actions": [
      {
        "type": "start_battle",
        "terrain": "none",
        "enemy_id": "agnes_hr",
        "win_target": "agnes_defeated",
        "lose_target": "lost_to_HR",
        "flee_target": "attempt_pass"
      }
    ],
    "textBlocks": [
      "Agnes lunges forward with surprising speed, her HR badge glinting under the red emergency lights.\n\n\"Let's see if your resignation letter is as strong as your resolve!\""
    ],
    "choices": [
      {
        "label": "Attack!",
        "target": "agnes_battle",
        "sfx": "thud.ogg",
        "battle_action": "attack"
      },
      {
        "label": "Skills",
        "target": "agnes_battle",
        "sfx": "click.ogg",
        "battle_action": "skill"
      },
      {
        "label": "Defend",
        "target": "agnes_battle",
        "sfx": "click.ogg",
        "battle_action": "defend"
      },
      {
        "label": "Item",
        "target": "agnes_battle",
        "sfx": "click.ogg",
        "battle_action": "item"
      }
    ]
  },
  "agnes_defeated": {
    "id": "agnes_defeated",
    "bg": "stairwell_escape.jpg",
    "music": "victory.mp3",
    "chars": [
      "agnes_surprised.svg"
    ],
    "textBlocks": [
      "Agnes staggers back, clutching her manila folder to her chest like a shield.\n\n\"I... I can't believe it. No one has ever resisted HR before.\"",
      "She drops the folder. Papers scatter across the floor - your \"exit interview\" forms, all pre-filled with answers you never gave.\n\n\"Fine. Go. But mark my words, Andy... HR *always* remembers.\"",
      "She retreats into the shadows of the stairwell. The path to freedom is clear."
    ],
    "choices": [
      {
        "label": "Run down the stairs before she changes her mind!",
        "target": "exit_lobby",
        "sfx": "footstep.ogg"
      }
    ]
  },
  "attempt_pass": {
    "id": "attempt_pass",
    "bg": "stairwell_landing.jpg",
    "music": "dicey_decisions.mp3",
    "chars": [
      "agnes_blocking.svg"
    ],
    "textBlocks": [
      "You mutter a quick \"Gotta run!\" and try to dart past Agnes.\n\nYou are fast, but Agnes is known to have a hidden history as a competitive ballroom dancer.",
      "**You must roll a d20 (13 or lower to succeed).**\n\nHow will you attempt to evade her?"
    ],
    "choices": [
      {
        "label": "Sprint past her! (Normal roll)",
        "target": "attempt_pass_normal",
        "sfx": "dice_roll.ogg"
      },
      {
        "label": "Throw coffee in her face first!",
        "target": "attempt_pass_advantage",
        "uses": [
          "Coffee Mug"
        ],
        "sfx": "gulp.ogg"
      },
      {
        "label": "Just try to squeeze by carefully...",
        "target": "attempt_pass_disadvantage",
        "sfx": "footstep.ogg"
      }
    ]
  },
  "attempt_pass_advantage": {
    "id": "attempt_pass_advantage",
    "bg": "stairwell_landing.jpg",
    "music": "dicey_decisions.mp3",
    "chars": [
      "agnes_surprised.svg"
    ],
    "actions": [
      {
        "type": "roll_dice",
        "dice": "d20",
        "threshold": 13,
        "modifier": "advantage",
        "skill": "Evasion (with Advantage!)",
        "crit_text": "\"Hot coffee AND a perfect dodge!\"",
        "fumble_text": "\"The coffee splashes... on YOU!\"",
        "success_target": "d20_success",
        "failure_target": "d20_failure"
      }
    ],
    "textBlocks": [
      "You hurl the hot coffee at Agnes! She recoils, temporarily blinded.\n\n**Rolling with ADVANTAGE!** (Roll twice, take the better result)"
    ],
    "choices": [
      {
        "label": "ROLL D20 WITH ADVANTAGE!",
        "target": "_roll",
        "sfx": "dice_roll.ogg"
      }
    ]
  },
  "attempt_pass_disadvantage": {
    "id": "attempt_pass_disadvantage",
    "bg": "stairwell_landing.jpg",
    "music": "dicey_decisions.mp3",
    "chars": [
      "agnes_blocking.svg"
    ],
    "actions": [
      {
        "type": "roll_dice",
        "dice": "d20",
        "threshold": 13,
        "modifier": "disadvantage",
        "skill": "Evasion (with Disadvantage)",
        "crit_text": "\"Against all odds, you slip through!\"",
        "fumble_text": "\"She saw that coming a mile away...\"",
        "success_target": "d20_success",
        "failure_target": "d20_failure"
      }
    ],
    "textBlocks": [
      "You try to sidle past slowly... but this gives Agnes plenty of time to anticipate your moves.\n\n**Rolling with DISADVANTAGE!** (Roll twice, take the worse result)"
    ],
    "choices": [
      {
        "label": "ROLL D20 WITH DISADVANTAGE...",
        "target": "_roll",
        "sfx": "dice_roll.ogg"
      }
    ]
  },
  "attempt_pass_normal": {
    "id": "attempt_pass_normal",
    "bg": "stairwell_landing.jpg",
    "music": "dicey_decisions.mp3",
    "chars": [
      "agnes_blocking.svg"
    ],
    "actions": [
      {
        "type": "roll_dice",
        "dice": "d20",
        "threshold": 13,
        "skill": "Evasion",
        "crit_text": "\"You move like the wind!\"",
        "fumble_text": "\"You trip over your own feet!\"",
        "success_target": "d20_success",
        "failure_target": "d20_failure"
      }
    ],
    "textBlocks": [
      "You take a deep breath and sprint!"
    ],
    "choices": [
      {
        "label": "ROLL D20...",
        "target": "_roll",
        "sfx": "dice_roll.ogg"
      }
    ]
  },
  "back_stairs": {
    "id": "back_stairs",
    "bg": "office_corridor.jpg",
    "music": "oh_oh.mp3",
    "chars": [
      "joni_desperate.svg",
      "norbert_pleading.svg"
    ],
    "textBlocks": [
      "You turn left toward the back stairwell, but before you reach it, you hear a frantic whispering from the office next door.\n\nTwo colleagues, Joni and Norbert, step out, looking desperate. Joni is frantically clutching a printed thesis draft.\n\n\"Andy! Thank God! You're the only one who knows the Bayesian Multi-Variate Regression with Inverse Propensity Weighting. My PhD submission is today, and it just crashed! Please, you have to help me!\""
    ],
    "choices": [
      {
        "label": "Sit at the desk and help them fix the model.",
        "target": "lost_to_PhD",
        "sfx": "click.ogg"
      },
      {
        "label": "Say, \"Sorry, guys, I'm out of here. Good luck.\"",
        "target": "colleague_plea",
        "sfx": "negative.ogg"
      },
      {
        "label": "Say, \"FUCK OFF.\"",
        "target": "corridor_safe",
        "sfx": "door_slam.ogg"
      }
    ]
  },
  "coffee_drunk": {
    "id": "coffee_drunk",
    "bg": "office_kitchen.jpg",
    "music": "spooky.mp3",
    "remove_items": [
      "Coffee Mug"
    ],
    "textBlocks": [
      "The coffee tastes strangely sweet. Too sweet. You lean against the counter, feeling satisfied...",
      "...and suddenly, incredibly drowsy.\n\nThe room begins to spin. Your vision blurs. The last thing you see is the coffee machine's display blinking: **\"EMPLOYEE RETENTION BREW - ACTIVATED\"**"
    ],
    "choices": [
      {
        "label": "The room is spinning. You close your eyes.",
        "target": "lost_to_coffee",
        "sfx": "thud.ogg"
      }
    ]
  },
  "coffee_kitchen": {
    "id": "coffee_kitchen",
    "bg": "office_kitchen.jpg",
    "music": "too_much_coffee.mp3",
    "add_items": [
      "Coffee Mug"
    ],
    "textBlocks": [
      "You step into the kitchen. It is eerily quiet. The coffee machine is running, smelling comfortingly familiar.",
      "You pour yourself a mug. The warmth feels good in your hands. You could drink it now... or save it for later.\n\n**You picked up a Coffee Mug!**"
    ],
    "choices": [
      {
        "label": "Drink it now. One last sip for the road.",
        "target": "coffee_drunk",
        "sfx": "gulp.ogg"
      },
      {
        "label": "Save it for later. Time to leave.",
        "target": "hallway_return",
        "sfx": "footstep.ogg"
      }
    ]
  },
  "colleague_plea": {
    "id": "colleague_plea",
    "bg": "office_corridor.jpg",
    "music": "questioning.mp3",
    "chars": [
      "joni_desperate.svg",
      "norbert_grabbing.svg"
    ],
    "textBlocks": [
      "Norbert grabs your sleeve.\n\n\"Please, Andy! Five minutes! You were always the best! If Joni misses the deadline, he loses everything!\""
    ],
    "choices": [
      {
        "label": "Agree: \"Fine, five minutes.\"",
        "target": "lost_to_PhD",
        "sfx": "click.ogg"
      },
      {
        "label": "Refuse again: \"No, I really have to go.\"",
        "target": "corridor_delayed",
        "sfx": "negative.ogg"
      }
    ]
  },
  "corridor_delayed": {
    "id": "corridor_delayed",
    "bg": "office_corridor.jpg",
    "music": "i_can_do_it.mp3",
    "chars": [
      "fabio_friendly.svg",
      "ali_friendly.svg"
    ],
    "textBlocks": [
      "You shake off Joni and step firmly into the corridor, only to be immediately intercepted by Fabio and Ali.\n\n\"Andy! Leaving already? Just wanted to say hello and wish you luck!\"\n\nAfter a few minutes of pleasantries, Ali adds, \"Oh, you didn't say bye to the fourth floor folks, did you? Michi, Gilles, and Ruling will never forgive you!\""
    ],
    "choices": [
      {
        "label": "Agree to take the elevator up to the 4th floor.",
        "target": "fourth_floor_elevator",
        "sfx": "elevator_ding.ogg"
      },
      {
        "label": "Say \"I don't have time!\" and run for the stairs.",
        "target": "corridor_safe",
        "sfx": "footstep.ogg"
      }
    ]
  },
  "corridor_safe": {
    "id": "corridor_safe",
    "bg": "back_stairwell_dim.jpg",
    "music": "zen.mp3",
    "textBlocks": [
      "Ignoring their desperate pleas, you walk past your former colleagues.\n\nThe hallway feels heavy with their disappointment, but you continue toward the dimly lit back stairwell.\n\nIt smells faintly of dust and cleaning supplies. You enjoy the silence of your final moments in the building."
    ],
    "choices": [
      {
        "label": "Continue down to the main entrance.",
        "target": "exit_lobby",
        "sfx": "footstep.ogg"
      }
    ]
  },
  "d20_failure": {
    "id": "d20_failure",
    "bg": "hallway_dim.jpg",
    "music": "spooky.mp3",
    "chars": [
      "agnes_victorious.svg"
    ],
    "textBlocks": [
      "You moved very fast, but Agnes is faster. Her leg snaps out with precision, and you trip, falling face down onto the carpet.\n\nThe wind is knocked out of you. Agnes calmly stands over you, holding the manila folder.\n\nBefore you can protest, she presses a button on her watch. The hallway lights dim. You wake up chained to your old desk."
    ],
    "choices": [
      {
        "label": "The long-term employment trap has sprung.",
        "target": "lost_to_coffee",
        "sfx": "chain.ogg"
      }
    ]
  },
  "d20_success": {
    "id": "d20_success",
    "bg": "stairwell_escape.jpg",
    "music": "running_escape.mp3",
    "chars": [
      "agnes_surprised.svg"
    ],
    "textBlocks": [
      "You weren't fast enough to catch her completely off guard, but you saw the movement!\n\nAgnes stretches her leg in a lightning-fast trip move. In a moment of great sportiveness (you? REALLY?), you leap over her extended foot with a surprising burst of agility.\n\nYou get a clean run to the main stairs!"
    ],
    "choices": [
      {
        "label": "Scramble down the main stairs to the entrance.",
        "target": "exit_lobby",
        "sfx": "footstep.ogg"
      }
    ]
  },
  "document_refusal": {
    "id": "document_refusal",
    "bg": "hallway_red_alert.jpg",
    "music": "BOSS_TIME.mp3",
    "chars": [
      "agnes_angry.svg"
    ],
    "textBlocks": [
      "You politely refuse to sign. Agnes's smile vanishes, replaced by an expression of cold, professional disapproval.\n\n\"I was hoping you'd cooperate, Andy. But if you insist on doing this the hard way...\"",
      "She cracks her knuckles. The hallway lights flicker to an ominous red.\n\n\"Did you know I was the regional ballroom dancing champion three years running? The footwork translates surprisingly well to... *corporate negotiations*.\"\n\nShe assumes a fighting stance that's equal parts waltz and martial arts."
    ],
    "choices": [
      {
        "label": "Stand your ground and fight!",
        "target": "agnes_battle",
        "sfx": "alert.ogg"
      },
      {
        "label": "Try to run past her!",
        "target": "attempt_pass",
        "sfx": "footstep.ogg"
      },
      {
        "label": "Fine, fine! I'll sign it!",
        "target": "document_signed",
        "sfx": "click.ogg"
      }
    ]
  },
  "document_signed": {
    "id": "document_signed",
    "bg": "stairwell_landing.jpg",
    "music": "legal_trap_stairwell.mp3",
    "chars": [
      "agnes_happy.svg"
    ],
    "textBlocks": [
      "You sigh, scribble your signature on the last page of the dense legal document, and hand the pen back to Agnes.\n\n\"All done, Andy! Best of luck,\" she chirps.\n\nYou are now free to take the stairs down, feeling only slightly heavier."
    ],
    "choices": [
      {
        "label": "Scramble down the main stairs to the entrance.",
        "target": "exit_lobby",
        "sfx": "footstep.ogg"
      }
    ]
  },
  "exit_lobby": {
    "id": "exit_lobby",
    "bg": "sunny_street_freedom.jpg",
    "music": "victory.mp3",
    "chars": [
      "security_guard_waving.svg"
    ],
    "textBlocks": [
      "You reach the main lobby. The security guard waves you goodbye.\n\nYou push open the heavy front doors and step out onto the street.\n\nThe sun is shining. The chapter is closed. **YOU WIN.**"
    ],
    "choices": []
  },
  "fourth_floor_elevator": {
    "id": "fourth_floor_elevator",
    "bg": "meeting_room_whiteboard.jpg",
    "music": "reading_papers.mp3",
    "chars": [
      "michi_whiteboard.svg",
      "gilles_explaining.svg",
      "ruling_pointing.svg"
    ],
    "textBlocks": [
      "You agree and press the \"4\" button. The ride up is silent.\n\nWhen the doors open, Michi, Gilles, and Ruling are there, ready to ambush you with a whiteboard.\n\nYou spend the next two agonizing hours discussing the optimal parameters for a highly complex, niche model. Your resolve slowly erodes."
    ],
    "choices": [
      {
        "label": "Finally manage to break free and get back on the elevator.",
        "target": "exit_lobby",
        "sfx": "elevator_ding.ogg"
      }
    ]
  },
  "hallway_return": {
    "id": "hallway_return",
    "bg": "hallway_fluorescent.jpg",
    "music": "last_day.mp3",
    "textBlocks": [
      "You step back into the hallway, coffee in hand. The warmth is comforting.\n\nAs you turn the corner, you nearly walk straight into Agnes from HR. She's standing right there, blocking the corridor.",
      "She holds a single, thick manila envelope and smiles a very thin smile.\n\n\"Andy. Perfect timing. Just a quick document I need you to sign before you are officially off the premises. Standard exit protocol.\""
    ],
    "choices": [
      {
        "label": "Sign the document without reading it.",
        "target": "document_signed",
        "sfx": "click.ogg"
      },
      {
        "label": "Refuse to sign and ask what it is.",
        "target": "document_refusal",
        "sfx": "negative.ogg"
      },
      {
        "label": "Try to walk around Agnes, pretending not to hear.",
        "target": "attempt_pass",
        "sfx": "footstep.ogg"
      }
    ]
  },
  "lost_to_coffee": {
    "id": "lost_to_coffee",
    "bg": "dark_office_desk.jpg",
    "music": "game_over.mp3",
    "textBlocks": [
      "You wake up with a throbbing headache. You are chained to your old desk chair.\n\nThe office is dark, except for the flickering screen of a monitor displaying a perpetual \"System Update\" message.\n\nYou realize you have been working here, unknowingly, for a very long time.\n\n**You lost the game.**"
    ],
    "choices": []
  },
  "lost_to_HR": {
    "id": "lost_to_HR",
    "bg": "bedroom_morning.jpg",
    "music": "game_over.mp3",
    "textBlocks": [
      "You wake up in your apartment, startled. The clock says 7:00 AM.\n\nYou feel an inexplicable dread about the long commute ahead of you.\n\nYou remember nothing about a \"new job\" or a \"last day.\" You are stuck in an endless loop of yesterday.\n\n**You lost the game.**"
    ],
    "choices": []
  },
  "lost_to_PhD": {
    "id": "lost_to_PhD",
    "bg": "desk_computer_code.jpg",
    "music": "game_over.mp3",
    "textBlocks": [
      "You sit down and dive into the code. The problem is deep, fascinating, and consumes your entire focus.\n\nYou hear the door swing shut, but you don't look up. You solve the bug, then another, and another.\n\nNext time you check the time, the digital clock reads: **2035**.\n\nYou cannot remember the names of the people who asked you for help. You have merged with the job.\n\n**You lost the game.**"
    ],
    "choices": []
  },
  "main_stairs": {
    "id": "main_stairs",
    "bg": "stairwell_landing.jpg",
    "music": "BOSS_TIME.mp3",
    "chars": [
      "agnes_neutral.svg"
    ],
    "textBlocks": [
      "You turn right and walk toward the main stairwell. Just as you reach the landing, Agnes from HR steps out, blocking your path.\n\nShe holds a single, thick manila envelope and smiles a very thin smile.\n\n\"Andy. Perfect timing. Just a quick document I need you to sign before you are officially off the premises. Standard exit protocol.\""
    ],
    "choices": [
      {
        "label": "Sign the document without reading it.",
        "target": "document_signed",
        "sfx": "click.ogg"
      },
      {
        "label": "Refuse to sign and ask what it is.",
        "target": "document_refusal",
        "sfx": "negative.ogg"
      },
      {
        "label": "Try to walk around Agnes, pretending not to hear.",
        "target": "attempt_pass",
        "sfx": "footstep.ogg"
      }
    ]
  },
  "start": {
    "id": "start",
    "bg": "hallway_fluorescent.jpg",
    "music": "last_day.mp3",
    "textBlocks": [
      "The old wooden door closes with a dull thud behind you for the very last time. Your badge no longer works; your desk is empty.",
      "You stand in the dim hallway of the 1st floor, where scuffed tile stretches ahead and the overhead fluorescents hum their familiar drone.\n\nYour new job starts Monday, and this chapter is finally closed. Now, you just need to get to the entrance and head out to freedom."
    ],
    "choices": [
      {
        "label": "Turn right and take the main stairs down to the entrance.",
        "target": "main_stairs",
        "sfx": "footstep.ogg"
      },
      {
        "label": "Turn left and take the back stairs to the main entrance.",
        "target": "back_stairs",
        "sfx": "footstep.ogg"
      },
      {
        "label": "Get one last, sentimental cup of coffee in the kitchen near your office.",
        "target": "coffee_kitchen",
        "sfx": "door_open.ogg"
      }
    ]
  }
};

// Export for use by engine
if (typeof module !== "undefined" && module.exports) {
    module.exports = { story };
}
