/**
 * Andi VN - Summon Data
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by tools/build_story_from_md.py
 * 
 * Edit summon files in summons/*.md instead.
 */

var summonDefinitions = {
  "office_intern": {
    "id": "office_intern",
    "name": "Office Intern",
    "sprite": "intern.svg",
    "icon": "\ud83d\udccb",
    "hp": 8,
    "ac": 8,
    "damage": "d4",
    "damageType": "physical",
    "attackBonus": 1,
    "duration": 4,
    "canProtect": true,
    "canAttack": true,
    "dialogue": {
      "summon_appear": [
        "You wanted to see me, Agnes?",
        "I brought coffee!",
        "Reporting for duty!"
      ],
      "attack": [
        "Filing this under 'urgent'!",
        "Let me handle this!",
        "I got it!"
      ],
      "protect": [
        "I'll take the hit!",
        "Not on my watch!",
        "Agnes needs me!"
      ],
      "low_hp": [
        "I... I need a break...",
        "This wasn't in my job description..."
      ],
      "death": [
        "I quit!",
        "I'm calling HR... wait...",
        "Unpaid overtime wasn't worth this..."
      ],
      "expire": [
        "My shift is over!",
        "Time to clock out!"
      ]
    },
    "moves": [
      {
        "name": "Coffee Run",
        "damage": "d4",
        "type": "physical",
        "description": "The intern throws hot coffee!"
      },
      {
        "name": "Paper Jam",
        "damage": "d3",
        "type": "physical",
        "statusEffect": {
          "type": "stun",
          "chance": 0.1
        },
        "description": "A stack of paperwork causes confusion!"
      }
    ],
    "description": "The hapless office intern, eternally stuck in a cycle of coffee runs and paperwork. They try their best to help Agnes, though their enthusiasm often outpaces their competence. At least they're eager?"
  },
  "sentient_keyboard": {
    "id": "sentient_keyboard",
    "name": "Sentient Keyboard",
    "sprite": "keyboard.svg",
    "icon": "\u2328",
    "hp": 12,
    "ac": 10,
    "damage": "d6",
    "damageType": "physical",
    "attackBonus": 2,
    "duration": 5,
    "canProtect": false,
    "canAttack": true,
    "dialogue": {
      "summon_appear": [
        "CLACK CLACK CLACK!",
        "*mechanical keyboard sounds*",
        "Ready to type some damage!"
      ],
      "attack": [
        "CLICK CLACK!",
        "*angry typing noises*",
        "asdfghjkl;!"
      ],
      "low_hp": [
        "*keys falling off*",
        "Need... new... keycaps..."
      ],
      "death": [
        "*sad beep*",
        "Error 404: Keyboard not found..."
      ],
      "expire": [
        "*powers down*",
        "Going into sleep mode..."
      ]
    },
    "moves": [
      {
        "name": "Key Smash",
        "damage": "d6",
        "type": "physical",
        "description": "The keyboard types furiously at the enemy!"
      },
      {
        "name": "Caps Lock",
        "damage": "d4",
        "type": "physical",
        "statusEffect": {
          "type": "stun",
          "chance": 0.15
        },
        "description": "AN ANGRY ALL-CAPS MESSAGE STUNS THE TARGET!"
      }
    ],
    "description": "A sentient mechanical keyboard that has gained consciousness through exposure to too many coffee spills and late-night coding sessions. It communicates primarily through aggressive typing sounds and occasionally coherent words."
  }
};

// Initialize BattleSummon module with definitions
if (typeof BattleSummon !== "undefined") {
    BattleSummon.init(summonDefinitions);
}

// Export for use by engine
if (typeof module !== "undefined" && module.exports) {
    module.exports = { summonDefinitions };
}
