/**
 * Andi VN - Theme Configuration
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by tools/build_story_from_md.py
 * 
 * Edit theme.md to change the selected theme.
 */

const themeConfig = {
  "selected": "90s",
  "available": [
    "prototype",
    "90s"
  ]
};

// Export for use by engine
if (typeof module !== "undefined" && module.exports) {
    module.exports = { themeConfig };
}
