#!/usr/bin/env python3
"""
Convert theme CSS files from separate files to body class format.
Outputs a unified themes.css file.
"""

import os
import re
from pathlib import Path

# Theme files to convert
THEMES_DIR = Path(__file__).parent.parent / "css" / "themes"
OUTPUT_FILE = Path(__file__).parent.parent / "css" / "themes.css"

def convert_theme_css(theme_name: str, css_content: str) -> str:
    """Convert a theme CSS file to body.theme-* format."""

    # Skip if file is empty or just comments
    if not css_content.strip():
        return ""

    lines = []
    lines.append(f"/* === {theme_name.upper()} THEME === */")
    lines.append("")

    # Extract :root variables and convert to body.theme-* variables
    root_match = re.search(r':root\s*\{([^}]+)\}', css_content, re.DOTALL)
    if root_match:
        root_vars = root_match.group(1).strip()
        lines.append(f"body.theme-{theme_name} {{")
        # Indent the variables
        for line in root_vars.split('\n'):
            line = line.strip()
            if line:
                lines.append(f"    {line}")
        lines.append("}")
        lines.append("")

    # Find all other selectors and prefix with body.theme-*
    # Remove :root block first
    remaining_css = re.sub(r':root\s*\{[^}]+\}', '', css_content)

    # Remove @keyframes (they don't need prefixing and should only be defined once)
    keyframes = re.findall(r'@keyframes\s+\w+\s*\{[^}]+(?:\{[^}]*\}[^}]*)*\}', remaining_css, re.DOTALL)
    remaining_css = re.sub(r'@keyframes\s+\w+\s*\{[^}]+(?:\{[^}]*\}[^}]*)*\}', '', remaining_css, flags=re.DOTALL)

    # Remove @supports blocks for now (complex nesting)
    remaining_css = re.sub(r'@supports[^{]+\{[^}]+(?:\{[^}]*\}[^}]*)*\}', '', remaining_css, flags=re.DOTALL)

    # Remove @media blocks for now (will handle separately)
    media_blocks = re.findall(r'@media[^{]+\{([^}]+(?:\{[^}]*\}[^}]*)*)\}', remaining_css, re.DOTALL)
    remaining_css = re.sub(r'@media[^{]+\{[^}]+(?:\{[^}]*\}[^}]*)*\}', '', remaining_css, flags=re.DOTALL)

    # Remove * { } reset block
    remaining_css = re.sub(r'\*\s*\{[^}]+\}', '', remaining_css)

    # Remove html { } block
    remaining_css = re.sub(r'html\s*\{[^}]+\}', '', remaining_css)

    # Process remaining selectors
    # Match selector { ... } blocks
    selector_pattern = r'([^{}]+)\{([^{}]+)\}'

    for match in re.finditer(selector_pattern, remaining_css):
        selector = match.group(1).strip()
        rules = match.group(2).strip()

        if not selector or not rules:
            continue

        # Skip comments
        if selector.startswith('/*'):
            continue

        # Handle multiple selectors (comma separated)
        selectors = [s.strip() for s in selector.split(',')]
        prefixed_selectors = []

        for sel in selectors:
            if not sel:
                continue
            # If selector starts with body, just add the theme class
            if sel.startswith('body'):
                prefixed_selectors.append(sel.replace('body', f'body.theme-{theme_name}', 1))
            else:
                prefixed_selectors.append(f'body.theme-{theme_name} {sel}')

        if prefixed_selectors:
            lines.append(f"{', '.join(prefixed_selectors)} {{")
            for rule in rules.split(';'):
                rule = rule.strip()
                if rule:
                    lines.append(f"    {rule};")
            lines.append("}")
            lines.append("")

    return '\n'.join(lines)


def main():
    """Convert all theme CSS files to unified themes.css."""

    output_lines = []
    output_lines.append("/**")
    output_lines.append(" * Andi VN - Unified Theme Styles")
    output_lines.append(" *")
    output_lines.append(" * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY")
    output_lines.append(" * Generated by tools/convert_themes.py")
    output_lines.append(" *")
    output_lines.append(" * All themes use body.theme-* class selectors.")
    output_lines.append(" * Theme is applied by adding class to <body> element.")
    output_lines.append(" */")
    output_lines.append("")

    # Get all theme CSS files
    theme_files = sorted(THEMES_DIR.glob("*.css"))

    print(f"Found {len(theme_files)} theme files")

    for theme_file in theme_files:
        theme_name = theme_file.stem  # filename without extension
        print(f"Processing: {theme_name}")

        with open(theme_file, 'r', encoding='utf-8') as f:
            css_content = f.read()

        converted = convert_theme_css(theme_name, css_content)
        if converted:
            output_lines.append(converted)
            output_lines.append("")

    # Write output
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(output_lines))

    print(f"\nGenerated: {OUTPUT_FILE}")
    print(f"Total lines: {len(output_lines)}")


if __name__ == "__main__":
    main()
